name: package:java_http CI

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'pkgs/java_http/**'
      - 'pkgs/http_client_conformance_tests/**'
      - '.github/workflows/java.yml'
  pull_request:
    paths:
      - 'pkgs/java_http/**'
      - 'pkgs/http_client_conformance_tests/**'
      - '.github/workflows/java.yml'
  schedule:
    - cron: "0 0 * * 0"
    
env:
  PUB_ENVIRONMENT: bot.github
        
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/java_http
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          # TODO: Change to 'stable' when a release version of flutter
          # pins version 1.21.1 or later of 'package:test'
          channel: 'master'
          
      - id: install
        name: Install dependencies
        run: dart pub get
        
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        if: always() && steps.install.outcome == 'success'
        
      - name: Analyze code
        run: dart analyze --fatal-infos
        if: always() && steps.install.outcome == 'success'
        
      - name: Build jni dynamic libraries 
        run: dart run jni:setup
        
      - name: Run tests
        run: dart test
